import { StyleSheet } from 'react-native';
import {
  Colors,
  Spacing,
  BorderRadius,
} from '../../../design-tokens';

export const styles = StyleSheet.create({
  container: {
    zIndex: 200,
  },
  gestureWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    maxHeight: '70%',
  } as const,
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.background,
  },
  menu: {
    backgroundColor: Colors.panelBackground,
    borderTopLeftRadius: BorderRadius.xl + 4,
    borderTopRightRadius: BorderRadius.xl + 4,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: Colors.borderSubtle,
  },
  handleContainer: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    cursor: 'grab',
  } as any,
  handle: {
    width: 36,
    height: 4,
    backgroundColor: Colors.borderSubtle,
    borderRadius: 2,
  },
  content: {
    paddingHorizontal: Spacing.xl,
  },
  section: {
    marginBottom: Spacing.xl + 4,
  },
  sectionTitle: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: Spacing.md,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  customEditor: {
    marginTop: Spacing.lg,
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  customEditorTitle: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: Spacing.md,
  },
  customColorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  customColorWrapper: {
    width: 34,
    height: 34,
    borderRadius: 17,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  customColorInput: {
    width: 46,
    height: 46,
    padding: 0,
    margin: -6,
    border: 'none',
    cursor: 'pointer',
    backgroundColor: 'transparent',
  } as any,
  customColorFallback: {
    width: '100%',
    height: '100%',
  },
  customActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  customActionBtn: {
    flex: 1,
    paddingVertical: Spacing.sm + 1,
    alignItems: 'center',
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.buttonBackground,
  },
  customActionText: {
    color: Colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  colorOption: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  colorSelectionRing: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
  },
  colorFrame: {
    width: 34,
    height: 34,
    borderRadius: 17,
    overflow: 'hidden',
    borderWidth: 1,
    backgroundColor: 'transparent',
  },
  colorCircle: {
    flex: 1,
  },
  customThemeBadge: {
    position: 'absolute',
    right: 1,
    bottom: 1,
    width: 15,
    height: 15,
    borderRadius: 7.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  customThemeBadgeText: {
    fontSize: 10,
    lineHeight: 10,
    fontWeight: '800',
  },
  shapeOption: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.buttonBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoOption: {
    width: 48,
    height: 48,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.buttonBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoUploadButton: {
    width: '100%',
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.buttonBackground,
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  logoUploadText: {
    color: Colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  logoSizeSection: {
    marginTop: Spacing.md,
  },
  logoSizeRow: {
    flexDirection: 'row',
    borderRadius: BorderRadius.md,
    padding: 3,
    alignSelf: 'flex-start',
    borderWidth: 1,
  },
  logoSizeOption: {
    minWidth: 42,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoSizeText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textSubtle,
    textTransform: 'uppercase',
  },
  logoSizeTextSelected: {
    color: '#2F2F2F',
  },
  logoEmoji: {
    fontSize: 22,
    color: Colors.textPrimary,
  },
  logoImage: {
    width: 28,
    height: 28,
  },
  gapRow: {
    flexDirection: 'row',
    backgroundColor: Colors.buttonBackground,
    borderRadius: BorderRadius.md,
    padding: 3,
    alignSelf: 'flex-start',
  },
  gapOption: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  gapText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.textSubtle,
    textTransform: 'uppercase',
  },
  gapTextSelected: {
    color: '#2F2F2F',
  },
});
